- .babelrc
- .eslintrc
- .gitignore
- .travis.yml
- examples/.eslintrc
- examples/basic/README.md
- examples/basic/package.json
- examples/basic/public/index.html
- examples/basic/src/index.js
- package.json
- src/ActionTypes.js
- src/BaseLink.js
- src/ElementsRenderer.js
- src/HttpError.js
- src/Link.js
- src/Matcher.js
- src/RedirectException.js
- src/createBaseRouter.js
- src/createBrowserRouter.js
- src/createConnectedLink.js
- src/createConnectedRouter.js
- src/createFarceRouter.js
- src/createMatchEnhancer.js
- src/createRender.js
- src/getRoutes.js
- src/matchReducer.js
- src/resolveElements.js
This is by no means full-fledged, but it's enough to demonstrate the basic concept.
> Initial implementation

- examples/transition-hook/README.md
- examples/transition-hook/package.json
- examples/transition-hook/public/index.html
- examples/transition-hook/src/index.js
- package.json
- src/PropTypes.js
- src/createBaseRouter.js
- src/createBrowserRouter.js
- src/createConnectedRouter.js
- src/createFarceRouter.js
This is really just exposing the method from farce, along with adding the example.
> Add transition hook support

- .travis.yml
We'll probably just use Jest here anyway.
> Remove unused browser configuration from Travis

- .eslintrc
- package.json
- src/jsx/__tests__/Redirect.test.js
- src/jsx/__tests__/Route.test.js
- src/jsx/__tests__/index.test.js
- src/jsx/__tests__/makeRouteConfig.test.js
Just started to write some tests for them. I hope this will be helpful.
> Set up Jest for jsx components and makeRouteConfig

- package.json
- src/__tests__/ActionTypes.test.js
- test/ActionTypes.test.js
- test/BaseLink.test.js
I am not sure we should use `enzyme` here, but IMO it make tests easier to read. Another Question is that how should we mock match and router objects?
> Tests (ActionTypes, BaseLink)

- src/ResolverUtils.js
- test/ResolverUtils.test.js
> Fix checkResolved

- README.md
Fixes https://github.com/4Catalyzer/found-relay/issues/16
> Fix SSR docs

- examples/basic-jsx/package-lock.json
- examples/basic-jsx/package.json
- examples/basic/package-lock.json
- examples/basic/package.json
- examples/global-pending/package-lock.json
- examples/global-pending/package.json
- examples/redux/package-lock.json
- examples/redux/package.json
- examples/transition-hook/package-lock.json
- examples/transition-hook/package.json
- examples/universal-redux/package-lock.json
- examples/universal-redux/package.json
- examples/universal/package-lock.json
- examples/universal/package.json
Use npm for Found for better npm@5 and Yarn compatibility.
> Update example dependencies

- examples/universal-redux/.babelrc
- examples/universal-redux/package.json
- examples/universal-redux/src/server.js
- examples/universal/.babelrc
- examples/universal/package.json
- examples/universal/src/server.js
> Fix universal examples

- src/BaseLink.js
> Mark to on <Link> as required

- test/BaseLink.test.js
- test/Matcher.test.js
Mostly from #100, with some stuff picked up from #107
> Improve tests

- .travis.yml
- codecov.yml
- package-lock.json
- package.json
The coverage isn't very good (not good enough to justify displaying a badge), but this will help track it for PRs.
> Add Codecov

- README.md
> Fix regex example in README [ci skip]

- package.json
- src/makeRouteConfig.js
- test/makeRouteConfig.test.js
- yarn.lock
This is just a failing test case for now.
> Fix proxy workaround for RHL v4

- README.md
- examples/hot-reloading/.babelrc
- examples/hot-reloading/README.md
- examples/hot-reloading/package-lock.json
- examples/hot-reloading/package.json
- examples/hot-reloading/src/BrowserRouter.js
- examples/hot-reloading/src/client.js
- examples/hot-reloading/src/routeConfig.js
- examples/hot-reloading/webpack.config.js
- src/Matcher.js
- src/createBaseRouter.js
- src/createMatchEnhancer.js
- src/hotRouteConfig.js
- src/index.js
- test/hotRouteConfig.test.js
- test/render.test.js
> Improve hot reloading support

- src/ResolverUtils.js
- src/index.js
- test/ResolverUtils.test.js
Unblocks https://github.com/4Catalyzer/found/issues/163, https://github.com/4Catalyzer/found-relay/issues/60.
cc @NSLS
> Add accumulateRouteValues

- src/makeRouteConfig.js
- test/makeRouteConfig.test.js
Closes https://github.com/4Catalyzer/found/issues/190
> Support fragments in makeRouteConfig

- README.md
- src/HttpError.js
- src/RedirectException.js
- src/createBaseRouter.js
- src/server/getFarceResult.js
- src/utils/resolveRenderArgs.js
> fix: Remove instanceof checks for errors

- src/ElementsRenderer.js
- test/render.test.js
> feat: Allow route render methods to return a function

- .babelrc
- package.json
- src/Matcher.js
- src/createBaseRouter.js
- src/getRenderArgs.js
- yarn.lock
~Requires https://github.com/babel/babel/pull/9650~
> chore: Upgrade to Babel 7

- package.json
- src/makeRouteConfig.js
- test/Router.test.js
- test/__snapshots__/makeRouteConfig.test.js.snap
- test/makeRouteConfig.test.js
- test/redirect.test.js
- test/render.test.js
> fix: Throw on invalid elements in JSX route configs

- src/BaseLink.js
- types/example-app/CustomLink.tsx
- types/index.d.ts
We could actually be more precise but it might still be too restrictive. this is the approach taken by [semantic-ui](https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/elements/Button/Button.d.ts#L16) and others
> fix: Fix <Link> typing

- types/ElementsRenderer.d.ts
- types/createRender.d.ts
- types/index.d.ts
> fix: Add types for ElementsRenderer

- src/createMatchEnhancer.js
This allows updating the location so that state/queries are present on POP or refresh but doesn't force a match
> feat: add terrible API for bypassing routing updates

- package.json
- yarn.lock
Noticed the CI is broken, two different versions were pointing to the same thing
edit: this seems to fix things for me locally, but on CI it fails still - will try it in a few hours to rule out NPM issues
> fix: fix ts-versions on CI

- examples/basic/package.json
- examples/basic/src/index.jsx
- examples/basic/yarn.lock
- src/Matcher.ts
- src/Route.ts
- src/createFarceRouter.js
- src/createFarceStore.js
- src/pathToRegexp.js
- src/typeUtils.ts
- www/docs/configuration/route-config.md
- www/docs/getting-started/quick-start.mdx
Adds a few dev warnings around common confusing route situations as well as a new `allowAsIndex` prop on Route
> feat: add dev warnings and support allowAsIndex on Route

- src/Redirect.tsx
- src/additional.d.ts
- src/createBaseRouter.tsx
- src/createConnectedRouter.tsx
- src/createFarceRouter.tsx
This one was the most painful to do :P
> feat: createBaseRouter in TS

- src/Link.tsx
- src/RouterContext.ts
- src/additional.d.ts
- src/createBaseRouter.tsx
- src/createFarceStore.ts
- src/server.tsx
- src/useLocation.ts
- src/useMatch.ts
- src/useParams.ts
- src/useRouter.ts
- src/withRouter.ts
another small batch. tried including `resolver` and `createElements` in here, but types for those have a bunch of small mismatches which makes it troublesome. will take another stab at 'em later
> feat: convert withRouter, server to TS

- .eslintignore
- CHANGELOG.md
- package.json
- www/docs/configuration/navigation.md
Resolves #987 
I've generated a changelog from git history so that the next release will include only commits between releases. Checked everything offline and everything seems to be working
> chore: add a changelog

- src/Link.tsx
- src/foundReducer.ts
> fix: pass className in Link
